### PR TITLE
Fix/70 storybook fixes adding components to editor

### LINKED ISSUE #70: Storybook fixes adding components to Editor
After trying to add components to Editor, I found some inconsistencies in components, that we should fix in order to use them in Editor.

Header component:
- Disclaimer should accept Disclaimer component or add Disclaimer component straight to Storybook 

SerachBar:
- onChange has different type

Footer:
- it works, but would be nice to add interactive date, that would change with years

### PR DESCRIPTION
**Pull request by DomyS**
## Related issue

Closes #70 

Fixes for Header, SearchBar, Footer.
I believe that there will be more fixes in the future for various components, but I think it's good idea to do it step by step in small amounts :)

### CODE REVIEW

File: src/components/Header/Header.tsx [hunk 1]
```diff
@@ -11,20 +11,18 @@ import { useMediaQuery } from '@mui/material';
 import MenuIcon from '@mui/icons-material/Menu';
 import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
 import ChevronRightIcon from '@mui/icons-material/ChevronRight';
-import Button from '../Button';
+import Logo from '../../img/Logo.png';
```
Comment (withchristopher) [inline src/components/Header/Header.tsx:14]: This needs to be a local file (in same folder), otherwise rollup will complain. 

Consider using absolute path, ie: `/img/Logo.png`

**Review by withchristopher — CHANGES_REQUESTED** [review]
Small change to the path.

File: src/components/Header/Header.tsx (hunk 1 above)
Comment (DomyS) [reply src/components/Header/Header.tsx:14]: You mean having Logo inside Header folder? or inside Components folder?

Comment (withchristopher) [reply src/components/Header/Header.tsx:14]: Review this Stackoverflow for clearer answer: https://stackoverflow.com/questions/57061414/rollup-changes-import-of-absolute-path-to-relative-path-while-bundling

Comment (DomyS) [reply src/components/Header/Header.tsx:14]: Do you know if there is a way to test it? Because I've added it same way as from the link you provided and I have no idea if it will work

Comment (withchristopher) [reply src/components/Header/Header.tsx:14]: The way I would test it is:

`npm run build`

Then you can try importing the package using the README guide. This is good for now. I will close this comment

File: src/components/SearchBar/SearchBar.tsx [hunk 2]
```diff
@@ -18,6 +22,7 @@ export interface SearchBarProps {
   error?: boolean;
   helperText?: string;
   sx?: object;
+  onKeyDown?: KeyboardEventHandler<HTMLDivElement>;
```
[the remark this answers is not in the document]
Comment (DomyS) [reply src/components/SearchBar/SearchBar.tsx]: That's really good suggestion!
Added fix 👍

**Review by tobiastykvart — APPROVED** [review]
LGTM
